version: '3'
services:
  flask_app:
    build: ./
    user: root
    volumes:
      - ./flask_app:/flask_app
    working_dir: /flask_app
    ports:
      - "8000:8000"
    command: python app.py
    environment:
        SEARCH_STRINGS: "${SEARCH_STRINGS}"
  stream_app:
    build: ./
    user: root
    volumes:
      - ./flask_app:/flask_app
    working_dir: /flask_app
    command: python stream_api.py
    environment:
        TWITTER_API_BEARER_TOKEN: "${TWITTER_API_BEARER_TOKEN}"
        SEARCH_STRINGS: "${SEARCH_STRINGS}"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
