version: '3'
services:
  flask_app:
    build: ./
    user: root
    volumes:
      - ./flask_app:/flask_app
    working_dir: /flask_app
    ports:
      - "5000:5000"
    command: python app.py
  stream_app:
    build: ./
    user: root
    volumes:
      - ./flask_app:/flask_app
    working_dir: /flask_app
    command: python stream_api.py
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"